### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by sgreenstein**
Add the Unlicense license from unlicense.org to clarify that this project is in the public domain.

You state [here](http://vjoystick.sourceforge.net/site/index.php/forum/5-Discussion/104-what-is-the-usage-license-for-this-software) that you would like vJoy to be in the public domain. This change would allow you to clarify that fact in the source. Please accept only if you would like to enable other developers to use vJoy as public domain.

### CODE REVIEW

**Comment by mirh** [comment]
Just for the records, GPL doesn't disallow commercial purposes.

**Comment by shauleiz** [comment]
I have about two or three requests for clarification a year. I send the requester a clear statement. I think this is good enough.

**Comment by WasabiFan** [comment]
> I have about two or three requests for clarification a year. I send the requester a clear statement. I think this is good enough.

If you are getting multiple requests a year, that means there are probably hundreds who have the question but are not willing to go out of their way and ask. Adding a license is an easy thing for you to do to ease that confusion.

**Comment by sgreenstein** [comment]
I'm likely one of many who cannot use your library because it's unlicensed, which is disappointing because it was very useful and easy to work with.

From Github help: "without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work"

If you reconsider and would like to add a license yourself, Github has instructions here: https://help.github.com/articles/adding-a-license-to-a-repository/

Thanks for your work!

**Comment by mirh** [comment]
"I don't give a fuck", seems the very legal definition of the WTFPL

**Comment by shauleiz** [comment]
MIT License. OK? Done.

**Pull request closed without merging**
